In [2]:
import numpy as np

In [4]:
arr = np.array([12, 23, 45, 56, 32])

In [6]:
arr

array([12, 23, 45, 56, 32])

In [8]:
print(arr)

[12 23 45 56 32]


In [10]:
type(arr)

numpy.ndarray

In [12]:
arr.dtype

dtype('int64')

In [14]:
arr = np.array([12, 23, 45, 56, 32, 66.22])

In [16]:
arr.dtype

dtype('float64')

In [18]:
arr

array([12.  , 23.  , 45.  , 56.  , 32.  , 66.22])

In [20]:
arr = np.array([12, 23, 45, 56, 32, 66.22, 'Pune'])

In [22]:
arr

array(['12', '23', '45', '56', '32', '66.22', 'Pune'], dtype='<U32')

In [24]:
%%timeit
arr = np.array([12, 23, 45, 56, 32, 66.22, 'Pune'])

3.08 µs ± 255 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [26]:
arr[3]

'56'

In [30]:
arr.shape

(7,)

In [32]:
arr = np.array([12, 23, 45, 56, 32])

In [34]:
arr * 2

array([ 24,  46,  90, 112,  64])

In [36]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [40]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [42]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
# 2d

In [48]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])

In [50]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
arr1.shape

(4, 3)

In [54]:
arr1.ndim

2

In [58]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
arr1.shape

(4, 3)

In [66]:
arr1.size

12

In [64]:
arr1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
arr1.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
arr1.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [72]:
arr1.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [74]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [76]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [78]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
arr1[0:3, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [82]:
arr

array([12, 23, 45, 56, 32])

In [84]:
arr.mean()

33.6

In [86]:
arr.min()

12

In [88]:
arr = np.array([1,3,5,6,3,3,1,7])

In [90]:
np.unique(arr)

array([1, 3, 5, 6, 7])

In [96]:
arr1 = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr1                

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
np.linalg.det(arr1)

-9.51619735392994e-16

In [100]:
np.linalg.inv(arr1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [102]:
arr2 = np.array([[1,5,3], [4,8,6],[7,12,11]])
arr2

array([[ 1,  5,  3],
       [ 4,  8,  6],
       [ 7, 12, 11]])

In [104]:
arr1 @ arr2

array([[ 30,  57,  48],
       [ 66, 132, 108],
       [102, 207, 168]])

In [106]:
arr1 * arr2

array([[ 1, 10,  9],
       [16, 40, 36],
       [49, 96, 99]])