In [1]:
import numpy as np

In [5]:
arr = np.array([23, 45, 12, 67, 34])

In [7]:
print(arr)

[23 45 12 67 34]


In [9]:
arr

array([23, 45, 12, 67, 34])

In [11]:
arr = np.array([23, 45, 12, 67, 34, 12.13])

In [17]:
arr.dtype

dtype('float64')

In [19]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 12.13])

In [15]:
type(arr)

numpy.ndarray

In [21]:
arr1 = np.array([23, 45, 12, 67, 34, 12.13, 'Pune'])

In [23]:
arr1

array(['23', '45', '12', '67', '34', '12.13', 'Pune'], dtype='<U32')

In [25]:
arr1[2]

'12'

In [27]:
%%timeit
arr1 = np.array([23, 45, 12, 67, 34, 12.13, 'Pune'])

2.85 µs ± 394 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [29]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 12.13])

In [31]:
arr.ndim

1

In [35]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [41]:
np.arange(2, 21, 2.5)

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [43]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# 2d array

In [47]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [49]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr2.shape

(4, 3)

In [53]:
arr2.size

12

In [55]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
arr2.ndim

2

In [59]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
arr2.shape

(4, 3)

In [63]:
arr2.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr2.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [67]:
arr2.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [69]:
arr2.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [71]:
arr2.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [73]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 12.13])

In [77]:
arr[1:4]

array([45., 12., 67.])

In [79]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [85]:
arr2[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr

array([23.  , 45.  , 12.  , 67.  , 34.  , 12.13])

In [89]:
arr = np.array([1,2,3,1,4,2,6,2,2])

In [91]:
np.unique(arr)

array([1, 2, 3, 4, 6])

In [101]:
arr3 = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [103]:
np.linalg.inv(arr3)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [105]:
arr2 @ arr3

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150],
       [138, 171, 204]])